[2025-04-05T16:32:20.294+0000] {processor.py:161} INFO - Started process (PID=161) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:32:20.313+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T16:32:20.320+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:32:20.318+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:32:20.514+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:32:20.498+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T16:32:20.518+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:32:20.730+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.499 seconds
[2025-04-05T16:32:51.198+0000] {processor.py:161} INFO - Started process (PID=166) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:32:51.200+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T16:32:51.202+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:32:51.202+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:32:51.270+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:32:51.262+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T16:32:51.272+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:32:51.704+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.512 seconds
[2025-04-05T16:33:22.962+0000] {processor.py:161} INFO - Started process (PID=171) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:33:22.992+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T16:33:23.004+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:33:23.003+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:33:23.722+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:33:23.544+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T16:33:23.804+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:33:24.178+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 1.231 seconds
[2025-04-05T16:33:55.266+0000] {processor.py:161} INFO - Started process (PID=176) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:33:55.286+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T16:33:55.297+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:33:55.296+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:33:55.598+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:33:55.568+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T16:33:55.601+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:33:55.822+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.576 seconds
[2025-04-05T16:34:26.919+0000] {processor.py:161} INFO - Started process (PID=181) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:34:26.924+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T16:34:26.927+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:34:26.926+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:34:27.102+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:34:27.063+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T16:34:27.120+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:34:27.264+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.357 seconds
[2025-04-05T16:34:58.160+0000] {processor.py:161} INFO - Started process (PID=186) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:34:58.162+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T16:34:58.164+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:34:58.163+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:34:58.211+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:34:58.201+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T16:34:58.213+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:34:58.504+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.352 seconds
[2025-04-05T16:35:29.438+0000] {processor.py:161} INFO - Started process (PID=191) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:35:29.452+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T16:35:29.460+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:35:29.458+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:35:29.645+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:35:29.625+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T16:35:29.649+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:35:29.989+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.564 seconds
[2025-04-05T16:36:01.646+0000] {processor.py:161} INFO - Started process (PID=196) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:36:02.047+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T16:36:02.337+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:36:02.336+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:36:02.422+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:36:02.406+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T16:36:02.552+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:36:03.182+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 2.786 seconds
[2025-04-05T16:36:33.571+0000] {processor.py:161} INFO - Started process (PID=201) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:36:33.577+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T16:36:33.583+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:36:33.582+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:36:33.704+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:36:33.688+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T16:36:33.712+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:36:33.826+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.266 seconds
[2025-04-05T16:37:04.513+0000] {processor.py:161} INFO - Started process (PID=206) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:37:04.517+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T16:37:04.522+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:37:04.521+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:37:04.581+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:37:04.574+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T16:37:04.587+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:37:05.273+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.767 seconds
[2025-04-05T16:37:35.810+0000] {processor.py:161} INFO - Started process (PID=211) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:37:35.811+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T16:37:35.813+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:37:35.813+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:37:35.857+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:37:35.850+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T16:37:35.860+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:37:35.906+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.102 seconds
[2025-04-05T16:38:06.844+0000] {processor.py:161} INFO - Started process (PID=216) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:38:06.847+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T16:38:06.850+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:38:06.849+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:38:07.049+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:38:06.965+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T16:38:07.066+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:38:07.373+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.538 seconds
[2025-04-05T16:38:38.039+0000] {processor.py:161} INFO - Started process (PID=221) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:38:38.042+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T16:38:38.048+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:38:38.047+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:38:38.126+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:38:38.115+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T16:38:38.130+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:38:38.202+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.171 seconds
[2025-04-05T16:39:08.589+0000] {processor.py:161} INFO - Started process (PID=226) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:39:08.591+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T16:39:08.593+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:39:08.593+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:39:08.649+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:39:08.641+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T16:39:08.653+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:39:08.809+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.226 seconds
[2025-04-05T16:39:39.846+0000] {processor.py:161} INFO - Started process (PID=231) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:39:39.863+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T16:39:39.876+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:39:39.875+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:39:40.531+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:39:40.477+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T16:39:40.540+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:39:40.802+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 1.000 seconds
[2025-04-05T16:40:11.040+0000] {processor.py:161} INFO - Started process (PID=236) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:40:11.054+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T16:40:11.079+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:40:11.078+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:40:11.186+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:40:11.177+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T16:40:11.189+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:40:11.264+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.241 seconds
[2025-04-05T16:40:41.499+0000] {processor.py:161} INFO - Started process (PID=241) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:40:41.501+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T16:40:41.503+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:40:41.503+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:40:41.565+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:40:41.555+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T16:40:41.568+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:40:41.624+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.133 seconds
[2025-04-05T16:41:12.007+0000] {processor.py:161} INFO - Started process (PID=246) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:41:12.009+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T16:41:12.011+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:41:12.010+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:41:12.060+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:41:12.053+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T16:41:12.063+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:41:12.114+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.115 seconds
[2025-04-05T16:41:42.824+0000] {processor.py:161} INFO - Started process (PID=251) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:41:42.827+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T16:41:42.833+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:41:42.832+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:41:42.899+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:41:42.889+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T16:41:42.902+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:41:42.968+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.151 seconds
[2025-04-05T16:42:13.152+0000] {processor.py:161} INFO - Started process (PID=256) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:42:13.154+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T16:42:13.157+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:42:13.157+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:42:13.487+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:42:13.220+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T16:42:13.491+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:42:13.597+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.450 seconds
[2025-04-05T16:42:44.347+0000] {processor.py:161} INFO - Started process (PID=261) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:42:44.363+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T16:42:44.376+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:42:44.375+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:42:45.105+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:42:45.066+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T16:42:45.109+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:42:45.193+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.873 seconds
[2025-04-05T16:43:16.318+0000] {processor.py:161} INFO - Started process (PID=266) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:43:16.325+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T16:43:16.329+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:43:16.327+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:43:16.461+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:43:16.443+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T16:43:16.467+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:43:16.592+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.292 seconds
[2025-04-05T16:43:47.409+0000] {processor.py:161} INFO - Started process (PID=271) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:43:47.417+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T16:43:47.427+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:43:47.426+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:43:47.851+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:43:47.835+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T16:43:47.857+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:43:48.065+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.674 seconds
[2025-04-05T16:44:18.539+0000] {processor.py:161} INFO - Started process (PID=276) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:44:18.541+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T16:44:18.548+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:44:18.547+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:44:18.639+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:44:18.626+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T16:44:18.643+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:44:19.161+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.631 seconds
[2025-04-05T16:44:49.797+0000] {processor.py:161} INFO - Started process (PID=281) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:44:49.800+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T16:44:49.803+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:44:49.802+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:44:49.953+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:44:49.946+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T16:44:49.956+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:44:50.137+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.350 seconds
[2025-04-05T16:45:20.247+0000] {processor.py:161} INFO - Started process (PID=286) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:45:20.249+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T16:45:20.251+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:45:20.250+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:45:20.410+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:45:20.371+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T16:45:20.415+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:45:20.843+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.603 seconds
[2025-04-05T16:45:51.125+0000] {processor.py:161} INFO - Started process (PID=291) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:45:51.127+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T16:45:51.129+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:45:51.129+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:45:51.213+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:45:51.205+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T16:45:51.216+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:45:51.265+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.152 seconds
[2025-04-05T16:49:16.779+0000] {processor.py:161} INFO - Started process (PID=160) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:49:16.810+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T16:49:16.832+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:49:16.825+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:49:17.226+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:49:17.212+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T16:49:17.229+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:49:17.379+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.847 seconds
[2025-04-05T16:49:48.017+0000] {processor.py:161} INFO - Started process (PID=165) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:49:48.024+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T16:49:48.033+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:49:48.029+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:49:48.558+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:49:48.526+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T16:49:48.574+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:49:48.760+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.828 seconds
[2025-04-05T16:50:19.465+0000] {processor.py:161} INFO - Started process (PID=170) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:50:19.471+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T16:50:19.477+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:50:19.475+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:50:19.633+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:50:19.620+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T16:50:19.650+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:50:19.771+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.413 seconds
[2025-04-05T16:50:50.441+0000] {processor.py:161} INFO - Started process (PID=175) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:50:50.444+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T16:50:50.447+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:50:50.446+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:50:50.518+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:50:50.508+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T16:50:50.525+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:50:50.612+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.182 seconds
[2025-04-05T16:51:21.102+0000] {processor.py:161} INFO - Started process (PID=180) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:51:21.135+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T16:51:21.145+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:51:21.143+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:51:21.292+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:51:21.281+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T16:51:21.297+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:51:21.433+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.427 seconds
[2025-04-05T16:51:54.144+0000] {processor.py:161} INFO - Started process (PID=185) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:51:54.213+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T16:51:54.229+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:51:54.227+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:51:55.257+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:51:55.102+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T16:51:55.263+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:51:56.464+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 2.520 seconds
[2025-04-05T16:52:27.186+0000] {processor.py:161} INFO - Started process (PID=190) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:52:27.194+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T16:52:27.200+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:52:27.198+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:52:27.306+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:52:27.295+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T16:52:27.309+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:52:27.406+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.291 seconds
[2025-04-05T16:52:57.595+0000] {processor.py:161} INFO - Started process (PID=195) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:52:57.597+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T16:52:57.600+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:52:57.599+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:52:57.654+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:52:57.647+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T16:52:57.656+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:52:57.820+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.234 seconds
[2025-04-05T16:53:28.031+0000] {processor.py:161} INFO - Started process (PID=200) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:53:28.033+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T16:53:28.036+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:53:28.035+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:53:28.093+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:53:28.086+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T16:53:28.096+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:53:28.168+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.146 seconds
[2025-04-05T16:53:58.349+0000] {processor.py:161} INFO - Started process (PID=205) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:53:58.352+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T16:53:58.359+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:53:58.355+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:53:58.424+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:53:58.412+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T16:53:58.427+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:53:58.482+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.145 seconds
[2025-04-05T16:54:29.305+0000] {processor.py:161} INFO - Started process (PID=210) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:54:29.307+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T16:54:29.311+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:54:29.310+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:54:29.383+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:54:29.369+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T16:54:29.386+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:54:29.475+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.177 seconds
[2025-04-05T16:55:00.073+0000] {processor.py:161} INFO - Started process (PID=215) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:55:00.089+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T16:55:00.102+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:55:00.099+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:55:00.280+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:55:00.263+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T16:55:00.284+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:55:00.431+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.475 seconds
[2025-04-05T16:55:30.729+0000] {processor.py:161} INFO - Started process (PID=220) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:55:30.742+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T16:55:30.745+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:55:30.744+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:55:30.970+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:55:30.946+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T16:55:30.980+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:55:31.090+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.404 seconds
[2025-04-05T16:56:01.479+0000] {processor.py:161} INFO - Started process (PID=225) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:56:01.481+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T16:56:01.483+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:56:01.482+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:56:01.561+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:56:01.552+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T16:56:01.565+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:56:01.632+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.162 seconds
[2025-04-05T16:56:32.990+0000] {processor.py:161} INFO - Started process (PID=230) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:56:33.000+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T16:56:33.006+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:56:33.005+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:56:33.090+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:56:33.075+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T16:56:33.093+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:56:33.471+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.489 seconds
[2025-04-05T16:57:04.332+0000] {processor.py:161} INFO - Started process (PID=235) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:57:04.335+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T16:57:04.338+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:57:04.337+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:57:04.383+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:57:04.376+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T16:57:04.387+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:57:04.437+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.112 seconds
[2025-04-05T16:57:34.721+0000] {processor.py:161} INFO - Started process (PID=240) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:57:34.724+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T16:57:34.727+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:57:34.726+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:57:34.780+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:57:34.773+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T16:57:34.783+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:57:34.841+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.131 seconds
[2025-04-05T16:58:06.871+0000] {processor.py:161} INFO - Started process (PID=245) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:58:06.899+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T16:58:06.953+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:58:06.944+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:58:07.990+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:58:07.819+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T16:58:08.007+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:58:08.413+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 1.900 seconds
[2025-04-05T16:58:39.281+0000] {processor.py:161} INFO - Started process (PID=250) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:58:39.284+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T16:58:39.287+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:58:39.286+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:58:39.333+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:58:39.327+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T16:58:39.335+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:58:39.519+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.245 seconds
[2025-04-05T16:59:10.189+0000] {processor.py:161} INFO - Started process (PID=255) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:59:10.205+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T16:59:10.211+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:59:10.210+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:59:11.123+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:59:11.044+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T16:59:11.188+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:59:11.454+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 1.344 seconds
[2025-04-05T16:59:41.591+0000] {processor.py:161} INFO - Started process (PID=260) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:59:41.594+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T16:59:41.597+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:59:41.596+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:59:41.667+0000] {logging_mixin.py:188} INFO - [2025-04-05T16:59:41.658+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T16:59:41.670+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T16:59:41.811+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.226 seconds
[2025-04-05T17:00:11.956+0000] {processor.py:161} INFO - Started process (PID=265) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:00:11.957+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:00:11.960+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:00:11.959+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:00:12.010+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:00:12.002+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:00:12.013+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:00:12.064+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.114 seconds
[2025-04-05T17:06:17.843+0000] {processor.py:161} INFO - Started process (PID=159) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:06:17.974+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:06:18.029+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:06:18.012+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:06:18.406+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:06:18.386+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:06:18.434+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:06:18.968+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 1.850 seconds
[2025-04-05T17:06:49.862+0000] {processor.py:161} INFO - Started process (PID=165) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:06:49.864+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:06:49.869+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:06:49.867+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:06:49.966+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:06:49.957+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:06:49.972+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:06:50.571+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.716 seconds
[2025-04-05T17:07:21.472+0000] {processor.py:161} INFO - Started process (PID=170) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:07:21.478+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:07:21.483+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:07:21.481+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:07:21.568+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:07:21.552+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:07:21.572+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:07:21.690+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.223 seconds
[2025-04-05T17:07:53.448+0000] {processor.py:161} INFO - Started process (PID=175) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:07:53.594+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:07:53.688+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:07:53.661+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:07:55.678+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:07:55.174+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:07:55.738+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:07:57.406+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 4.230 seconds
[2025-04-05T17:08:27.759+0000] {processor.py:161} INFO - Started process (PID=180) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:08:27.772+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:08:27.781+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:08:27.778+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:08:27.907+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:08:27.895+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:08:27.912+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:08:28.130+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.422 seconds
[2025-04-05T17:08:59.392+0000] {processor.py:161} INFO - Started process (PID=185) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:08:59.394+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:08:59.397+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:08:59.396+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:08:59.439+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:08:59.432+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:08:59.441+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:08:59.585+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.606 seconds
[2025-04-05T17:09:31.463+0000] {processor.py:161} INFO - Started process (PID=190) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:09:31.491+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:09:31.503+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:09:31.500+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:09:32.129+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:09:32.087+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:09:32.138+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:09:32.633+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 1.294 seconds
[2025-04-05T17:10:02.839+0000] {processor.py:161} INFO - Started process (PID=195) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:10:02.842+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:10:02.844+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:10:02.843+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:10:02.896+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:10:02.889+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:10:02.899+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:10:02.990+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.159 seconds
[2025-04-05T17:10:33.255+0000] {processor.py:161} INFO - Started process (PID=200) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:10:33.258+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:10:33.261+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:10:33.260+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:10:33.339+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:10:33.329+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:10:33.345+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:10:33.404+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.160 seconds
[2025-04-05T17:11:04.032+0000] {processor.py:161} INFO - Started process (PID=205) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:11:04.034+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:11:04.036+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:11:04.036+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:11:04.173+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:11:04.156+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:11:04.178+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:11:04.489+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.465 seconds
[2025-04-05T17:11:34.685+0000] {processor.py:161} INFO - Started process (PID=210) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:11:34.687+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:11:34.690+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:11:34.689+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:11:34.736+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:11:34.729+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:11:34.738+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:11:34.838+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.158 seconds
[2025-04-05T17:12:05.052+0000] {processor.py:161} INFO - Started process (PID=215) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:12:05.064+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:12:05.070+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:12:05.068+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:12:05.151+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:12:05.145+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:12:05.153+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:12:05.198+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.152 seconds
[2025-04-05T17:12:35.517+0000] {processor.py:161} INFO - Started process (PID=220) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:12:35.520+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:12:35.522+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:12:35.522+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:12:35.581+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:12:35.573+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:12:35.584+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:12:35.631+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.133 seconds
[2025-04-05T17:13:05.962+0000] {processor.py:161} INFO - Started process (PID=225) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:13:05.964+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:13:05.970+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:13:05.966+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:13:06.037+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:13:06.026+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:13:06.040+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:13:06.171+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.223 seconds
[2025-04-05T17:13:36.833+0000] {processor.py:161} INFO - Started process (PID=230) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:13:36.853+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:13:36.856+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:13:36.855+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:13:37.586+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:13:37.578+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:13:37.589+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:13:38.487+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 1.674 seconds
[2025-04-05T17:14:08.872+0000] {processor.py:161} INFO - Started process (PID=235) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:14:08.876+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:14:08.881+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:14:08.880+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:14:09.067+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:14:09.022+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:14:09.089+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:14:09.261+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.402 seconds
[2025-04-05T17:14:39.599+0000] {processor.py:161} INFO - Started process (PID=240) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:14:39.606+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:14:39.616+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:14:39.610+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:14:39.784+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:14:39.767+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:14:39.788+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:14:40.084+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.628 seconds
[2025-04-05T17:15:10.950+0000] {processor.py:161} INFO - Started process (PID=245) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:15:10.975+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:15:10.994+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:15:10.986+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:15:11.128+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:15:11.117+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:15:11.132+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:15:11.262+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.390 seconds
[2025-04-05T17:15:41.344+0000] {processor.py:161} INFO - Started process (PID=250) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:15:41.345+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:15:41.347+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:15:41.347+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:15:41.430+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:15:41.419+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:15:41.435+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:15:41.855+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.517 seconds
[2025-04-05T17:16:12.132+0000] {processor.py:161} INFO - Started process (PID=255) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:16:12.136+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:16:12.139+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:16:12.138+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:16:12.327+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:16:12.289+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:16:12.341+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:16:12.590+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.479 seconds
[2025-04-05T17:16:43.273+0000] {processor.py:161} INFO - Started process (PID=260) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:16:43.286+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:16:43.289+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:16:43.288+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:16:43.372+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:16:43.355+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:16:43.374+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:16:43.513+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.248 seconds
[2025-04-05T17:17:14.136+0000] {processor.py:161} INFO - Started process (PID=265) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:17:14.138+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:17:14.143+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:17:14.142+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:17:14.190+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:17:14.182+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:17:14.192+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:17:14.308+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.181 seconds
[2025-04-05T17:17:45.090+0000] {processor.py:161} INFO - Started process (PID=270) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:17:45.093+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:17:45.107+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:17:45.104+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:17:45.208+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:17:45.196+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:17:45.214+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:17:45.330+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.257 seconds
[2025-04-05T17:18:15.985+0000] {processor.py:161} INFO - Started process (PID=275) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:18:16.000+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:18:16.008+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:18:16.007+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:18:16.279+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:18:16.102+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:18:16.619+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:18:18.418+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 2.422 seconds
[2025-04-05T17:18:49.767+0000] {processor.py:161} INFO - Started process (PID=280) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:18:49.770+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:18:49.780+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:18:49.779+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:18:50.096+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:18:50.031+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:18:50.111+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:18:50.253+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.507 seconds
[2025-04-05T17:19:20.874+0000] {processor.py:161} INFO - Started process (PID=285) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:19:20.887+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:19:20.892+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:19:20.890+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:19:21.032+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:19:21.014+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:19:21.036+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:19:21.281+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.616 seconds
[2025-04-05T17:19:51.501+0000] {processor.py:161} INFO - Started process (PID=290) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:19:51.505+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:19:51.507+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:19:51.506+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:19:51.691+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:19:51.677+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:19:51.695+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:19:51.871+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.386 seconds
[2025-04-05T17:20:22.230+0000] {processor.py:161} INFO - Started process (PID=295) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:20:22.234+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:20:22.237+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:20:22.236+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:20:22.307+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:20:22.297+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:20:22.312+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:20:22.401+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.183 seconds
[2025-04-05T17:20:53.012+0000] {processor.py:161} INFO - Started process (PID=300) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:20:53.093+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:20:53.096+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:20:53.095+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:20:53.167+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:20:53.157+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:20:53.172+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:20:53.243+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.241 seconds
[2025-04-05T17:21:23.719+0000] {processor.py:161} INFO - Started process (PID=305) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:21:23.721+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:21:23.724+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:21:23.723+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:21:23.823+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:21:23.812+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:21:23.826+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:21:23.973+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.265 seconds
[2025-04-05T17:21:54.686+0000] {processor.py:161} INFO - Started process (PID=310) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:21:54.689+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:21:54.692+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:21:54.690+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:21:54.807+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:21:54.799+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:21:54.813+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:21:54.884+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.211 seconds
[2025-04-05T17:22:25.168+0000] {processor.py:161} INFO - Started process (PID=315) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:22:25.172+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:22:25.175+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:22:25.174+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:22:25.241+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:22:25.229+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:22:25.244+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:22:25.322+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.162 seconds
[2025-04-05T17:22:56.073+0000] {processor.py:161} INFO - Started process (PID=320) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:22:56.078+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:22:56.080+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:22:56.080+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:22:56.145+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:22:56.135+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:22:56.149+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:22:56.211+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.146 seconds
[2025-04-05T17:23:27.611+0000] {processor.py:161} INFO - Started process (PID=325) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:23:27.618+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:23:27.689+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:23:27.639+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:23:28.002+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:23:27.811+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:23:28.008+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:23:28.514+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.921 seconds
[2025-04-05T17:23:58.680+0000] {processor.py:161} INFO - Started process (PID=330) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:23:58.686+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:23:58.693+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:23:58.691+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:23:58.781+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:23:58.772+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:23:58.788+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:23:59.007+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.341 seconds
[2025-04-05T17:24:29.398+0000] {processor.py:161} INFO - Started process (PID=335) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:24:29.402+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:24:29.404+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:24:29.403+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:24:29.453+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:24:29.445+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:24:29.456+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:24:29.527+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.136 seconds
[2025-04-05T17:24:59.730+0000] {processor.py:161} INFO - Started process (PID=340) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:24:59.732+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:24:59.734+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:24:59.733+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:24:59.795+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:24:59.786+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:24:59.798+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:24:59.851+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.127 seconds
[2025-04-05T17:25:30.180+0000] {processor.py:161} INFO - Started process (PID=345) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:25:30.182+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:25:30.184+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:25:30.183+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:25:30.234+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:25:30.226+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:25:30.236+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:25:30.292+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.117 seconds
[2025-04-05T17:26:00.629+0000] {processor.py:161} INFO - Started process (PID=350) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:26:00.631+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:26:00.633+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:26:00.632+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:26:00.685+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:26:00.678+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:26:00.689+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:26:00.750+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.126 seconds
[2025-04-05T17:26:31.217+0000] {processor.py:161} INFO - Started process (PID=355) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:26:31.220+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:26:31.223+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:26:31.222+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:26:31.285+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:26:31.276+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:26:31.289+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:26:31.434+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.225 seconds
[2025-04-05T17:27:01.866+0000] {processor.py:161} INFO - Started process (PID=360) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:27:01.870+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:27:01.873+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:27:01.872+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:27:01.988+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:27:01.969+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:27:01.992+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:27:02.107+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.256 seconds
[2025-04-05T17:27:32.532+0000] {processor.py:161} INFO - Started process (PID=365) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:27:32.535+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:27:32.537+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:27:32.536+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:27:32.596+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:27:32.587+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:27:32.599+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:27:32.661+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.137 seconds
[2025-04-05T17:28:02.890+0000] {processor.py:161} INFO - Started process (PID=370) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:28:02.893+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:28:02.895+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:28:02.894+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:28:02.943+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:28:02.935+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:28:02.946+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:28:02.998+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.112 seconds
[2025-04-05T17:28:33.385+0000] {processor.py:161} INFO - Started process (PID=375) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:28:33.388+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:28:33.391+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:28:33.390+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:28:33.455+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:28:33.444+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:28:33.460+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:28:33.563+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.185 seconds
[2025-04-05T17:29:03.734+0000] {processor.py:161} INFO - Started process (PID=380) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:29:03.736+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:29:03.739+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:29:03.738+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:29:03.781+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:29:03.775+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:29:03.783+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:29:03.856+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.126 seconds
[2025-04-05T17:29:34.316+0000] {processor.py:161} INFO - Started process (PID=385) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:29:34.318+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:29:34.322+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:29:34.321+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:29:34.360+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:29:34.354+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:29:34.362+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:29:34.406+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.096 seconds
[2025-04-05T17:30:04.711+0000] {processor.py:161} INFO - Started process (PID=390) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:30:04.713+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:30:04.716+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:30:04.715+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:30:04.769+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:30:04.761+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:30:04.773+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:30:04.825+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.127 seconds
[2025-04-05T17:30:35.200+0000] {processor.py:161} INFO - Started process (PID=395) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:30:35.202+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:30:35.204+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:30:35.203+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:30:35.248+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:30:35.241+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:30:35.251+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:30:35.297+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.101 seconds
[2025-04-05T17:31:05.651+0000] {processor.py:161} INFO - Started process (PID=400) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:31:05.654+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:31:05.656+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:31:05.655+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:31:05.701+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:31:05.695+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:31:05.704+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:31:05.752+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.107 seconds
[2025-04-05T17:31:36.245+0000] {processor.py:161} INFO - Started process (PID=405) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:31:36.246+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:31:36.248+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:31:36.248+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:31:36.295+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:31:36.287+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:31:36.297+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:31:36.342+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.102 seconds
[2025-04-05T17:32:06.792+0000] {processor.py:161} INFO - Started process (PID=410) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:32:06.798+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:32:06.802+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:32:06.801+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:32:06.868+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:32:06.859+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:32:06.871+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:32:06.936+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.156 seconds
[2025-04-05T17:32:37.636+0000] {processor.py:161} INFO - Started process (PID=415) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:32:37.641+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:32:37.644+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:32:37.643+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:32:37.723+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:32:37.711+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:32:37.727+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:32:37.796+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.168 seconds
[2025-04-05T17:33:08.033+0000] {processor.py:161} INFO - Started process (PID=420) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:33:08.035+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:33:08.037+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:33:08.037+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:33:08.094+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:33:08.080+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:33:08.097+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:33:08.167+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.140 seconds
[2025-04-05T17:33:38.678+0000] {processor.py:161} INFO - Started process (PID=425) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:33:38.680+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:33:38.682+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:33:38.682+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:33:38.731+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:33:38.721+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:33:38.733+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:33:38.789+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.117 seconds
[2025-04-05T17:34:09.383+0000] {processor.py:161} INFO - Started process (PID=430) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:34:09.387+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:34:09.389+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:34:09.389+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:34:09.444+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:34:09.437+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:34:09.447+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:34:09.492+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.115 seconds
[2025-04-05T17:34:39.782+0000] {processor.py:161} INFO - Started process (PID=435) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:34:39.805+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:34:39.823+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:34:39.822+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:34:39.961+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:34:39.920+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:34:39.967+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:34:40.033+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.287 seconds
[2025-04-05T17:35:11.172+0000] {processor.py:161} INFO - Started process (PID=440) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:35:11.185+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:35:11.195+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:35:11.194+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:35:11.465+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:35:11.446+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:35:11.469+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:35:11.562+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.398 seconds
[2025-04-05T17:35:41.729+0000] {processor.py:161} INFO - Started process (PID=445) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:35:41.731+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:35:41.739+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:35:41.738+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:35:41.824+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:35:41.810+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:35:41.826+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:35:41.924+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.202 seconds
[2025-04-05T17:36:12.708+0000] {processor.py:161} INFO - Started process (PID=450) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:36:12.719+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:36:12.724+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:36:12.722+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:36:13.086+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:36:13.072+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:36:13.090+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:36:13.250+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.560 seconds
[2025-04-05T17:36:43.450+0000] {processor.py:161} INFO - Started process (PID=455) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:36:43.453+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:36:43.455+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:36:43.454+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:36:43.520+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:36:43.512+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:36:43.526+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:36:43.590+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.145 seconds
[2025-04-05T17:37:14.493+0000] {processor.py:161} INFO - Started process (PID=460) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:37:14.500+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:37:14.506+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:37:14.504+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:37:14.573+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:37:14.566+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:37:14.576+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:37:14.644+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.158 seconds
[2025-04-05T17:37:44.844+0000] {processor.py:161} INFO - Started process (PID=465) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:37:44.846+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:37:44.848+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:37:44.848+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:37:44.905+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:37:44.898+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:37:44.908+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:37:44.961+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.126 seconds
[2025-04-05T17:38:15.241+0000] {processor.py:161} INFO - Started process (PID=470) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:38:15.242+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:38:15.244+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:38:15.244+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:38:15.290+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:38:15.281+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:38:15.293+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:38:15.341+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.106 seconds
[2025-04-05T17:38:45.738+0000] {processor.py:161} INFO - Started process (PID=475) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:38:45.739+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:38:45.741+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:38:45.741+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:38:45.787+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:38:45.780+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:38:45.790+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:38:45.841+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.108 seconds
[2025-04-05T17:39:16.165+0000] {processor.py:161} INFO - Started process (PID=480) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:39:16.167+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:39:16.169+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:39:16.168+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:39:16.248+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:39:16.229+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:39:16.252+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:39:16.361+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.201 seconds
[2025-04-05T17:39:46.615+0000] {processor.py:161} INFO - Started process (PID=485) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:39:46.617+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:39:46.619+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:39:46.619+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:39:46.666+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:39:46.658+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:39:46.669+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:39:46.714+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.103 seconds
[2025-04-05T17:40:17.058+0000] {processor.py:161} INFO - Started process (PID=490) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:40:17.060+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:40:17.064+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:40:17.062+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:40:17.132+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:40:17.120+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:40:17.135+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:40:17.188+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.136 seconds
[2025-04-05T17:40:47.738+0000] {processor.py:161} INFO - Started process (PID=495) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:40:47.741+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:40:47.743+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:40:47.742+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:40:47.812+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:40:47.800+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:40:47.816+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:40:47.892+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.159 seconds
[2025-04-05T17:41:18.102+0000] {processor.py:161} INFO - Started process (PID=500) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:41:18.103+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:41:18.105+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:41:18.104+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:41:18.146+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:41:18.140+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:41:18.148+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:41:18.193+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.099 seconds
[2025-04-05T17:41:48.800+0000] {processor.py:161} INFO - Started process (PID=505) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:41:48.805+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:41:48.807+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:41:48.806+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:41:48.948+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:41:48.898+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:41:48.968+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:41:49.065+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.273 seconds
[2025-04-05T17:42:19.426+0000] {processor.py:161} INFO - Started process (PID=510) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:42:19.431+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:42:19.450+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:42:19.449+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:42:19.537+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:42:19.527+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:42:19.540+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:42:19.591+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.171 seconds
[2025-04-05T17:42:50.136+0000] {processor.py:161} INFO - Started process (PID=515) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:42:50.138+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:42:50.141+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:42:50.140+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:42:50.189+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:42:50.180+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:42:50.193+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:42:50.255+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.130 seconds
[2025-04-05T17:43:20.668+0000] {processor.py:161} INFO - Started process (PID=520) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:43:20.670+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:43:20.672+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:43:20.671+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:43:20.721+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:43:20.713+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:43:20.724+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:43:20.768+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.105 seconds
[2025-04-05T17:43:51.187+0000] {processor.py:161} INFO - Started process (PID=525) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:43:51.190+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:43:51.194+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:43:51.193+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:43:51.254+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:43:51.247+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:43:51.260+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:43:51.318+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.137 seconds
[2025-04-05T17:44:21.673+0000] {processor.py:161} INFO - Started process (PID=530) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:44:21.675+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:44:21.677+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:44:21.676+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:44:21.720+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:44:21.713+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:44:21.722+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:44:21.769+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.101 seconds
[2025-04-05T17:44:52.690+0000] {processor.py:161} INFO - Started process (PID=535) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:44:52.692+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:44:52.697+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:44:52.696+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:44:52.756+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:44:52.748+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:44:52.760+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:44:52.940+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.255 seconds
[2025-04-05T17:45:23.152+0000] {processor.py:161} INFO - Started process (PID=540) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:45:23.155+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:45:23.158+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:45:23.157+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:45:23.247+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:45:23.229+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:45:23.259+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:45:23.379+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.236 seconds
[2025-04-05T17:45:53.986+0000] {processor.py:161} INFO - Started process (PID=545) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:45:54.016+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:45:54.028+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:45:54.025+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:45:54.103+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:45:54.095+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:45:54.107+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:45:54.283+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.399 seconds
[2025-04-05T17:46:25.012+0000] {processor.py:161} INFO - Started process (PID=550) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:46:25.091+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:46:25.176+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:46:25.172+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:46:25.626+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:46:25.602+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:46:25.630+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:46:25.776+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.816 seconds
[2025-04-05T17:46:56.682+0000] {processor.py:161} INFO - Started process (PID=555) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:46:56.694+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:46:56.698+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:46:56.697+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:46:56.838+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:46:56.818+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:46:56.847+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:46:56.962+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.292 seconds
[2025-04-05T17:47:27.372+0000] {processor.py:161} INFO - Started process (PID=560) to work on /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:47:27.377+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_to_snowflake_dag.py for tasks to queue
[2025-04-05T17:47:27.391+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:47:27.389+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:47:27.538+0000] {logging_mixin.py:188} INFO - [2025-04-05T17:47:27.507+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/ingest_to_snowflake_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_to_snowflake_dag.py", line 11, in <module>
    from bookshop.ingest_postgres_to_snowflake import load_data_to_snowflake  # Vérifier que ce module existe et est accessible
ModuleNotFoundError: No module named 'bookshop'
[2025-04-05T17:47:27.548+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_to_snowflake_dag.py
[2025-04-05T17:47:27.674+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_to_snowflake_dag.py took 0.335 seconds
