[0m14:34:49.302798 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002544AE52150>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002544AE500E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002544AE50140>]}


============================== 14:34:49.310845 | 7635d8ad-3060-40ec-b7b6-568bc94e1bbb ==============================
[0m14:34:49.310845 [info ] [MainThread]: Running with dbt=1.9.4
[0m14:34:49.313816 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Mari√©ta\\.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt init dbt', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m14:35:38.484879 [debug] [MainThread]: Starter project path: C:\Users\Mari√©ta\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\include\starter_project
[0m14:35:38.543742 [info ] [MainThread]: 
Your new dbt project "bookshop_dbt" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m14:35:38.545742 [info ] [MainThread]: Setting up your profile.
[0m14:35:45.246836 [error] [MainThread]: Encountered an error:
list index out of range
[0m14:35:45.253833 [error] [MainThread]: Traceback (most recent call last):
  File "C:\Users\Mari√©ta\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\cli\requires.py", line 153, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mari√©ta\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\cli\requires.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mari√©ta\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\cli\main.py", line 477, in init
    results = task.run()
              ^^^^^^^^^^
  File "C:\Users\Mari√©ta\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\task\init.py", line 346, in run
    self.setup_profile(profile_name)
  File "C:\Users\Mari√©ta\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\task\init.py", line 261, in setup_profile
    adapter = self.ask_for_adapter_choice()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mari√©ta\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\task\init.py", line 243, in ask_for_adapter_choice
    return available_adapters[numeric_choice - 1]
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range

[0m14:35:45.259816 [debug] [MainThread]: Command `dbt init` failed at 14:35:45.259816 after 56.29 seconds
[0m14:35:45.265811 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000254483CF380>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002544A9363F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002544A824770>]}
[0m14:35:45.277343 [debug] [MainThread]: Flushing usage events
[0m14:35:46.041750 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:36:40.851918 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000296F582F5F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000296F378C620>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000296F378E2D0>]}


============================== 14:36:40.859575 | bf1340fd-c307-460c-98ba-602f14e80fc2 ==============================
[0m14:36:40.859575 [info ] [MainThread]: Running with dbt=1.9.4
[0m14:36:40.861575 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Mari√©ta\\.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt init bookshop_dbt', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m14:36:40.944123 [info ] [MainThread]: A project called bookshop_dbt already exists here.
[0m14:36:40.953125 [debug] [MainThread]: Command `dbt init` succeeded at 14:36:40.952121 after 0.43 seconds
[0m14:36:40.955124 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000296F542B6E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000296F5CAB1A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000296F596FC80>]}
[0m14:36:40.957121 [debug] [MainThread]: Flushing usage events
[0m14:36:41.581008 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:37:08.274780 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001634A5835C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001634C660DA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001634BCAC3E0>]}


============================== 14:37:08.283205 | 66ce90d1-065f-47bc-aa12-6602fb0138f0 ==============================
[0m14:37:08.283205 [info ] [MainThread]: Running with dbt=1.9.4
[0m14:37:08.285144 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\Mari√©ta\\.dbt', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt init dbt', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m14:37:19.418117 [debug] [MainThread]: Starter project path: C:\Users\Mari√©ta\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\include\starter_project
[0m14:37:19.474876 [info ] [MainThread]: 
Your new dbt project "bookshop_dbt" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m14:37:19.477898 [info ] [MainThread]: Setting up your profile.
[0m14:40:30.340207 [info ] [MainThread]: Profile bookshop_dbt written to C:\Users\Mari√©ta\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m14:40:30.346208 [debug] [MainThread]: Command `dbt init` succeeded at 14:40:30.345223 after 202.37 seconds
[0m14:40:30.350212 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001634C0B7AA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001634C8DB080>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016349360EC0>]}
[0m14:40:30.359208 [debug] [MainThread]: Flushing usage events
[0m14:40:31.175026 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:08:07.593689 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002136D8B0860>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002136A765460>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000213700C3740>]}


============================== 15:08:07.675090 | e177c66a-ed8f-41c2-8b0b-c71069f52bb6 ==============================
[0m15:08:07.675090 [info ] [MainThread]: Running with dbt=1.9.4
[0m15:08:07.679944 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Mari√©ta\\.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run --full-refresh', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:08:07.683571 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Mari√©ta\Desktop\bookshop\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:08:07.696997 [debug] [MainThread]: Command `dbt run` failed at 15:08:07.695964 after 1.64 seconds
[0m15:08:07.700350 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021370883380>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002137096B7D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002137096B9E0>]}
[0m15:08:07.703041 [debug] [MainThread]: Flushing usage events
[0m15:08:09.231291 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:15:24.631607 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000219243F15E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002191EAC55E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000219246CB6E0>]}


============================== 15:15:24.651449 | 2f423a0e-0d68-4444-a9c5-41c1eaf023c4 ==============================
[0m15:15:24.651449 [info ] [MainThread]: Running with dbt=1.9.4
[0m15:15:24.655269 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': 'C:\\Users\\Mari√©ta\\.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run --full-refresh', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m15:15:24.658326 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Mari√©ta\Desktop\bookshop\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:15:24.674984 [debug] [MainThread]: Command `dbt run` failed at 15:15:24.673977 after 0.66 seconds
[0m15:15:24.677999 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002192443F6B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002192443F8C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000219249677A0>]}
[0m15:15:24.680002 [debug] [MainThread]: Flushing usage events
[0m15:15:25.453893 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m16:04:28.267582 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C85C2379B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C85F0FC0B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C85B960A10>]}


============================== 16:04:28.486282 | a48c8afb-8f08-4305-ab38-ee56c53e0875 ==============================
[0m16:04:28.486282 [info ] [MainThread]: Running with dbt=1.9.4
[0m16:04:28.489261 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': 'C:\\Users\\Mari√©ta\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'invocation_command': 'dbt run --full-refresh', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m16:04:28.492269 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Mari√©ta\Desktop\bookshop\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:04:28.498258 [debug] [MainThread]: Command `dbt run` failed at 16:04:28.497257 after 1.73 seconds
[0m16:04:28.500261 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C85B960A10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C85F132690>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C85F067FB0>]}
[0m16:04:28.503258 [debug] [MainThread]: Flushing usage events
[0m16:04:29.365597 [debug] [MainThread]: An error was encountered while trying to flush usage events
