[0m18:51:26.968998 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024560EFF4A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002455E8D9190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024560EFCFB0>]}


============================== 18:51:26.999859 | f5e57309-d0bb-449a-813d-862415286ed3 ==============================
[0m18:51:26.999859 [info ] [MainThread]: Running with dbt=1.9.4
[0m18:51:27.002823 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Mari√©ta\\.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt test --select +stg_ventes', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m18:51:27.005823 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Mari√©ta\Desktop\bookshop\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m18:51:27.009823 [debug] [MainThread]: Command `dbt test` failed at 18:51:27.008824 after 0.43 seconds
[0m18:51:27.012338 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002455DAC0C80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002455E8D9190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024560D49A30>]}
[0m18:51:27.013361 [debug] [MainThread]: Flushing usage events
[0m18:51:27.860732 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m23:38:17.644042 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F1E18D35F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F1E1976390>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F1E1B9B1A0>]}


============================== 23:38:17.661811 | cf79f7be-1d7c-40a7-a614-f7b636202380 ==============================
[0m23:38:17.661811 [info ] [MainThread]: Running with dbt=1.9.4
[0m23:38:17.664813 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Mari√©ta\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt run --full-refresh', 'send_anonymous_usage_stats': 'True'}
[0m23:38:17.665812 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Mari√©ta\Desktop\bookshop\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m23:38:17.670355 [debug] [MainThread]: Command `dbt run` failed at 23:38:17.669362 after 0.46 seconds
[0m23:38:17.672348 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F1E1976390>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F1E1545C40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F1E0E3B6E0>]}
[0m23:38:17.674351 [debug] [MainThread]: Flushing usage events
[0m23:38:18.576001 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m19:44:36.549899 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000011A24427B30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000011A26F93530>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000011A26F93830>]}


============================== 19:44:36.563853 | 7c6aa6db-0147-45e3-a5e9-3e539caa9576 ==============================
[0m19:44:36.563853 [info ] [MainThread]: Running with dbt=1.9.4
[0m19:44:36.566823 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Mari√©ta\\.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt run --full-refresh', 'send_anonymous_usage_stats': 'True'}
[0m19:44:36.568833 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Mari√©ta\Desktop\bookshop\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m19:44:36.571843 [debug] [MainThread]: Command `dbt run` failed at 19:44:36.571843 after 0.36 seconds
[0m19:44:36.572849 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000011A27444110>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000011A24427B30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000011A248C2BA0>]}
[0m19:44:36.573827 [debug] [MainThread]: Flushing usage events
[0m19:44:37.341602 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:47:43.797871 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D644C3A1E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D644590FB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D647376B40>]}


============================== 13:47:43.808929 | 5da1b0ff-8c67-46e1-bb19-80401eb98b55 ==============================
[0m13:47:43.808929 [info ] [MainThread]: Running with dbt=1.9.4
[0m13:47:43.810912 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Mari√©ta\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt clean', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m13:47:43.812908 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Mari√©ta\Desktop\bookshop\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:47:43.815917 [debug] [MainThread]: Command `dbt clean` failed at 13:47:43.815917 after 0.43 seconds
[0m13:47:43.816913 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D647407A40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D64729ED80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D6475B7B90>]}
[0m13:47:43.817917 [debug] [MainThread]: Flushing usage events
[0m13:47:44.667871 [debug] [MainThread]: An error was encountered while trying to flush usage events
